### ISSUE TITLE
您的代码有问题，按照您的步骤去做了

### ISSUE THREAD

**Issue by Javanbe** [heroWang/ZHIHU-Robot#3]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1386, in
_inlineCallbacks
    result = g.send(result)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 95, in crawl
    six.reraise(*exc_info)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 77, in crawl
    self.engine = self._create_engine()
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 102, in _create_e
ngine
    return ExecutionEngine(self, lambda _: self.stop())
  File "c:\python27\lib\site-packages\scrapy\core\engine.py", line 69, in __init
__
    self.downloader = downloader_cls(crawler)
  File "c:\python27\lib\site-packages\scrapy\core\downloader\__init__.py", line
88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "c:\python27\lib\site-packages\scrapy\middleware.py", line 58, in from_cr
awler
    return cls.from_settings(crawler.settings, crawler)
  File "c:\python27\lib\site-packages\scrapy\middleware.py", line 34, in from_se
ttings
    mwcls = load_object(clspath)
  File "c:\python27\lib\site-packages\scrapy\utils\misc.py", line 44, in load_ob
ject
    mod = import_module(module)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\python27\lib\site-packages\scrapy\downloadermiddlewares\retry.py", li
ne 20, in <module>
    from twisted.web.client import ResponseFailed
  File "c:\python27\lib\site-packages\twisted\web\client.py", line 42, in <modul
e>
    from twisted.internet.endpoints import HostnameEndpoint, wrapClientTLS
  File "c:\python27\lib\site-packages\twisted\internet\endpoints.py", line 41, i
n <module>
    from twisted.internet.stdio import StandardIO, PipeAddress
  File "c:\python27\lib\site-packages\twisted\internet\stdio.py", line 30, in <m
odule>
    from twisted.internet import _win32stdio
  File "c:\python27\lib\site-packages\twisted\internet\_win32stdio.py", line 9,
in <module>
    import win32api
ImportError: No module named win32api

cmd 运行以后 出现如上问题

**Comment by hong123123** [comment]
安装一下win32api这个包？
